Mobile version
microhass/portfolio pull request #3
Opened 2023-05-02 14:27 UTC by hassanShakur

Added form validations as per specified requirements.

2023-05-02 14:32 UTC, Olamarx requested changes
Hi @hassanShakur, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the contribution of your partner, kindly ensure that your partner(s) contribute to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-02 15:45 UTC, Gambit142 requested changes
Hi @hassanShakur @arnoldnekemiah 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Good Use of HTML validations ✔️ 
- Good use of form input types ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-02 15:45 UTC, Gambit142 commented on index.html
> +        >
- [ ] Based on the requirement, the max length for the `textarea` tag should be `500` and not `5000`. Kindly implement the validation as specified in the project's requirements. 👍

2023-05-02 15:45 UTC, Gambit142 commented on index.html
>          >
- [ ] Please use a placeholder with the text _**Write me something**_ instead of using the text  _**Write me something**_ as the default value of the `textarea` element. 👍

2023-05-02 15:45 UTC, Gambit142 commented on index.html
> +        >
- [ ] The form should be submitted to [Formspree](https://formspree.io/html/) API. To implement this successfully, you need to visit the Formspree service page, create an ID and then follow the instruction on the Formspree landing page to be able to submit the user's data to the Formspree service. The value for the `action` attribute of the `form` tag should be equal to the API endpoint plus the ID you create, and the `method` attribute of the `form` tag should have a value of `post`. 👍 💻 

#### Hint:

![image](https://user-images.githubusercontent.com/77106962/235716158-a0191a1e-7ef7-458b-9187-a05e546ef226.png)

2023-05-03 10:02 UTC, divinecharlotte approved these changes
# Hello @hassanShakur   😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- No linters errors ✔️
- Good implementation of the required changes👍 





## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 10:12 UTC, merged